//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace HIMS.Data.EntityClasses
{
	/// <summary>Class which represents the entity 'RefactorLog'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class RefactorLog : CommonEntityBase
	{
		#region Class Extensibility Methods
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="RefactorLog"/> class.</summary>
		public RefactorLog() : base()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the OperationKey field. </summary>
		[DataMember]
		public System.Guid OperationKey { get; set;}
		#endregion
	}
}
