//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace HIMS.Data.EntityClasses
{
	/// <summary>Class which represents the entity 'TaskState'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class TaskState : CommonEntityBase
	{
		#region Class Extensibility Methods
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="TaskState"/> class.</summary>
		public TaskState() : base()
		{
			this.UserTasks = new HashSet<UserTask>();
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the StateId field. </summary>
		[DataMember]
		public System.Int32 StateId { get; set;}
		/// <summary>Gets or sets the StateName field. </summary>
		[DataMember]
		public System.String StateName { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'UserTask.TaskState - TaskState.UserTasks (m:1)'</summary>
		[DataMember]
		public virtual ICollection<UserTask> UserTasks { get; set;}
		#endregion
	}
}
