//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace HIMS.Data.EntityClasses
{
	/// <summary>Class which represents the entity 'VUserProfile'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class VUserProfile : CommonEntityBase
	{
		#region Class Extensibility Methods
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="VUserProfile"/> class.</summary>
		public VUserProfile() : base()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the Address field. </summary>
		[DataMember]
		public System.String Address { get; set;}
		/// <summary>Gets or sets the Age field. </summary>
		[DataMember]
		public Nullable<System.Int32> Age { get; set;}
		/// <summary>Gets or sets the Direction field. </summary>
		[DataMember]
		public System.String Direction { get; set;}
		/// <summary>Gets or sets the Education field. </summary>
		[DataMember]
		public System.String Education { get; set;}
		/// <summary>Gets or sets the Email field. </summary>
		[DataMember]
		public System.String Email { get; set;}
		/// <summary>Gets or sets the FullName field. </summary>
		[DataMember]
		public System.String FullName { get; set;}
		/// <summary>Gets or sets the MathScore field. </summary>
		[DataMember]
		public Nullable<System.Double> MathScore { get; set;}
		/// <summary>Gets or sets the MobilePhone field. </summary>
		[DataMember]
		public System.String MobilePhone { get; set;}
		/// <summary>Gets or sets the Sex field. </summary>
		[DataMember]
		public System.String Sex { get; set;}
		/// <summary>Gets or sets the Skype field. </summary>
		[DataMember]
		public System.String Skype { get; set;}
		/// <summary>Gets or sets the StartDate field. </summary>
		[DataMember]
		public System.DateTime StartDate { get; set;}
		/// <summary>Gets or sets the UniversityAverageScore field. </summary>
		[DataMember]
		public Nullable<System.Double> UniversityAverageScore { get; set;}
		/// <summary>Gets or sets the UserId field. </summary>
		[DataMember]
		public System.Int32 UserId { get; set;}
		#endregion
	}
}
