CREATE TABLE [dbo].[TaskTrack]
(
	[TaskTrackId] INT IDENTITY NOT NULL, 
    [UserTaskId] INT NOT NULL, 
	[TrackDate] DATE NOT NULL,
	[TrackNote] NVARCHAR(MAX) NOT NULL

	CONSTRAINT [FK_UserTaskId] FOREIGN KEY ([UserTaskId]) REFERENCES [UserTask]([UserTaskId]) ON DELETE CASCADE ON UPDATE CASCADE 
)

